### ISSUE TITLE
add *.pyc to .gitignore

### ISSUE THREAD

**Issue by ghost** [an-OK-squirrel/scg#1]
^^

also what is this

**Comment by an-OK-squirrel** [comment]
k, will do
a code golf language

**Comment by matthewr6** [comment]
`.pyc` is a "compiled" python when imports call modules

**Comment by an-OK-squirrel** [comment]
Ik i thought they were only in pycache

**Comment by ghost** [comment]
I think **pycache** is only in Python 3, where Python 2 just spurts random .pyc files in the directory which is really terrible and horrible

**Comment by matthewr6** [comment]
It "spurts" whenever the file is being imported.

**Comment by ghost** [comment]
still terrible lol

**Comment by matthewr6** [comment]
I think they're the same lol

**Comment by ghost** [comment]
lol lol

**Comment by an-OK-squirrel** [comment]
spam lol but thanks will fix

**Comment by matthewr6** [comment]
ololol
